# Generated by Django 4.2.25 on 2025-11-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='between_streets',
            field=models.CharField(blank=True, max_length=200, verbose_name='entre calles'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='locality',
            field=models.CharField(blank=True, max_length=100, verbose_name='localidad'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=50, verbose_name='teléfono principal'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=50, verbose_name='teléfono secundario'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='código postal'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='calle'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
    ]
