# Generated by Django 4.2.25 on 2025-11-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_grade_alter_subject_weekly_hours_presential_and_more'),
        ('teachers', '0002_teacher_between_streets_teacher_locality_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_materials', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('course', 'subject')},
            },
        ),
    ]
