# Generated by Django 4.2.25 on 2025-10-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('IN', 'Ingreso'), ('EX', 'Egreso'), ('AJ', 'Ajuste')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'permissions': [('manage_adjustments', 'Can add/change adjustments')],
            },
        ),
        migrations.CreateModel(
            name='MonthPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'permissions': [('close_month', 'Can close month for cooperadora')],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
