# Generated by Django 4.2.25 on 2025-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nombre')),
                ('weekly_hours_presential', models.PositiveIntegerField(default=0, verbose_name='carga horaria presencial (hs/sem)')),
                ('weekly_hours_tutoring', models.PositiveIntegerField(blank=True, null=True, verbose_name='carga horaria tutoría (hs/sem)')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
    ]
