# Generated by Django 4.2.25 on 2025-11-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(choices=[('1', '1ero'), ('2', '2do'), ('3', '3ro')], default='1', max_length=2, verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weekly_hours_presential',
            field=models.PositiveIntegerField(default=0, verbose_name='módulos semanales presenciales'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='weekly_hours_tutoring',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='módulos semanales de tutoría'),
        ),
    ]
